#!/bin/bash
# =============================================================================
# Script  : 05 - Manifest Generator
# Concepts: read (user input), file writing (> and >>), variables, date
# Purpose : Collect project info interactively and save to a manifest file
# Usage   : bash 05_manifest_generator.sh
# =============================================================================

echo "=============================================="
echo "       PROJECT MANIFEST GENERATOR"
echo "=============================================="
echo ""

# ----- Define output file with timestamp -----

TIMESTAMP=$(date '+%Y%m%d_%H%M%S')
OUTPUT="manifest_${TIMESTAMP}.txt"

# =============================================================================
# Section 1: Collect info from user using read
# read -r -p "prompt" VARIABLE — reads user input into a variable
# =============================================================================

echo "Enter project details below:"
echo ""
read -r -p "  Project Name     : " PROJECT_NAME
read -r -p "  Author Name      : " AUTHOR_NAME
read -r -p "  Roll Number      : " ROLL_NUMBER
read -r -p "  Department       : " DEPARTMENT
read -r -p "  University       : " UNIVERSITY
read -r -p "  Audited Software : " AUDITED_SOFTWARE
read -r -p "  License Type     : " LICENSE_TYPE
read -r -p "  Supervisor       : " SUPERVISOR

echo ""
echo "Fill in the template below for your description:"
read -r -p "  What does open source mean to you? : " FREEDOM
read -r -p "  What Linux tool do you use daily?  : " TOOL
read -r -p "  What project would you like to build? : " BUILD

DATE=$(date '+%Y-%m-%d')
PARAGRAPH="On $DATE, I believe open source means $FREEDOM. I use $TOOL daily, and I would love to build $BUILD and share it freely with the world."

echo ""

# ----- Auto-detected system info -----

SYS_USER=$(whoami)
SYS_HOST=$(hostname)
SYS_OS=$(uname -o 2>/dev/null || uname -s)
SYS_KERNEL=$(uname -r)
SYS_DATE=$(date '+%Y-%m-%d %H:%M:%S')

# =============================================================================
# Section 2: Write manifest to file
# First echo uses > (create/overwrite the file)
# All subsequent echo use >> (append to the file)
# =============================================================================

echo "--- Writing manifest... ---"

# > creates the file (or overwrites if it exists)
echo "==============================================================" > "$OUTPUT"
echo "  PROJECT MANIFEST" >> "$OUTPUT"
echo "  Generated: $SYS_DATE" >> "$OUTPUT"
echo "==============================================================" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# >> appends to the file
echo "--- Project Information ---" >> "$OUTPUT"
echo "  Project Name     : ${PROJECT_NAME:-N/A}" >> "$OUTPUT"
echo "  Author           : ${AUTHOR_NAME:-N/A}" >> "$OUTPUT"
echo "  Roll Number      : ${ROLL_NUMBER:-N/A}" >> "$OUTPUT"
echo "  Department       : ${DEPARTMENT:-N/A}" >> "$OUTPUT"
echo "  University       : ${UNIVERSITY:-N/A}" >> "$OUTPUT"
echo "  Audited Software : ${AUDITED_SOFTWARE:-Apache HTTPD}" >> "$OUTPUT"
echo "  License          : ${LICENSE_TYPE:-MIT}" >> "$OUTPUT"
echo "  Supervisor       : ${SUPERVISOR:-N/A}" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# Write the paragraph description to file
echo "--- Description ---" >> "$OUTPUT"
echo "  $PARAGRAPH" >> "$OUTPUT"
echo "" >> "$OUTPUT"

echo "--- System Information ---" >> "$OUTPUT"
echo "  Generated By     : $SYS_USER@$SYS_HOST" >> "$OUTPUT"
echo "  Operating System  : $SYS_OS" >> "$OUTPUT"
echo "  Kernel            : $SYS_KERNEL" >> "$OUTPUT"
echo "" >> "$OUTPUT"

# ----- List all scripts in the project -----

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ADVANCED_DIR="$(dirname "$SCRIPT_DIR")/advanced"

echo "--- Required Scripts ---" >> "$OUTPUT"
for SCRIPT in "$SCRIPT_DIR"/*.sh; do
    if [ -f "$SCRIPT" ]; then
        echo "  - $(basename "$SCRIPT")" >> "$OUTPUT"
    fi
done
echo "" >> "$OUTPUT"

echo "--- Advanced Scripts ---" >> "$OUTPUT"
if [ -d "$ADVANCED_DIR" ]; then
    for SCRIPT in "$ADVANCED_DIR"/*.sh; do
        if [ -f "$SCRIPT" ]; then
            echo "  - $(basename "$SCRIPT")" >> "$OUTPUT"
        fi
    done
else
    echo "  (none found)" >> "$OUTPUT"
fi
echo "" >> "$OUTPUT"

echo "==============================================================" >> "$OUTPUT"
echo "  END OF MANIFEST" >> "$OUTPUT"
echo "==============================================================" >> "$OUTPUT"

# =============================================================================
# Section 3: Show the saved file using cat
# =============================================================================

echo ""
echo "  Manifest saved to: $OUTPUT"
echo ""
echo "--- File Contents ---"
echo ""

cat "$OUTPUT"

echo ""
echo "=============================================="
echo "  Manifest generation complete."
echo "=============================================="
